steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/coachkip-site:$COMMIT_SHA", "."]

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/coachkip-site:$COMMIT_SHA"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "coachkip-site"
      - "--image=gcr.io/$PROJECT_ID/coachkip-site:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"

# Store the image in Container Registry
images:
  - "gcr.io/$PROJECT_ID/coachkip-site:$COMMIT_SHA"
